services:
#    upload.example:
#        class: UploadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    upload.function:
        class: UploadBundle\Service\FileUploaded
        arguments: ['%upload_directory%']