PetanqueBundle\Entity\Tournament:
    type: entity
    table: null
    repositoryClass: PetanqueBundle\Repository\TournamentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255

    manyToMany:
        players:
            targetEntity: PetanqueBundle\Entity\Player
            mappedBy: tournaments